const express = require("express")
const router = express.Router()
const userController = require('../controllers/UserController')
const { authAdminMiddleWare, authUserMiddleWare, authMemberMiddleWare } = require("../middleware/authMiddleware")

router.post('/sign-up', userController.createUser)
router.post('/sign-in', userController.loginUser)
router.post('/log-out', userController.logoutUser)
router.put('/update-user/:user',authUserMiddleWare, userController.updateUser)
router.put('/admin-update-user/:user',authAdminMiddleWare, userController.adminUpdateUser)
router.delete('/delete/:user', authAdminMiddleWare, userController.deleteUser)
router.get('/getAllUser',authAdminMiddleWare, userController.getAll)
router.get('/getMember',authAdminMiddleWare, userController.getAllMember)
router.get('/getCustomer',authMemberMiddleWare, userController.getAllCustomer)
router.get('/getUsersInfo', userController.getUsersInfo)
router.get('/get-detail/:user',authUserMiddleWare, userController.getDetailsUser)
router.get('/admin-get-detail/:user',authMemberMiddleWare, userController.getDetailsUser)
router.post('/refresh-token', userController.refreshToken)
module.exports = router